apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tree-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/treeservice(/|$)(.*)"
        backend:
          service:
            name: treeservice
            port:
              number: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: treeservice
  labels:
    app: treeservice
spec:
  type: ClusterIP
  selector:
    app: treeservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: treeservice
  labels:
    app: treeservice
spec:
  selector:
    matchLabels:
      app: treeservice
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: treeservice
    
    spec:
      containers:
      - name: treeservice
        image: treeservice
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
---
